{
 "title": "IoT Overview",
 "tags": [ "iot" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "DB Buzzer",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "query": "import \"experimental\"\n\nbuzz = from(bucket: \"sensors\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"DB\")\n  |> filter(fn: (r) => r[\"_field\"] == \"state\")\n  |> filter(fn: (r) => r[\"device\"] == \"iot-edge-01\")\n  |> filter(fn: (r) => r[\"pi_id\"] == \"PI1\")\n  |> map(fn: (r) => ({ r with _value: if r._value == \"buzz\" then 1 else 0 }))\n\nbuzz_zero_after = buzz\n  |> map(fn: (r) => ({ r with _value: 0, _time: experimental.addDuration(d: 1s, to: r._time) }))\n\nunion(tables: [buzz, buzz_zero_after])\n  |> sort(columns: [\"_time\"])\n  |> yield(name: \"state\")\n"
    }
   ]
  },
  {
   "title": "DL Sensor",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "query": "from(bucket: \"sensors\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"DL\")\n  |> filter(fn: (r) => r[\"_field\"] == \"state\")\n  |> filter(fn: (r) => r[\"device\"] == \"iot-edge-01\")\n  |> filter(fn: (r) => r[\"pi_id\"] == \"PI1\")\n  |> map(fn: (r) => ({ r with _value: if r._value == \"led_on\" then 1 else 0 }))\n  |> yield(name: \"state\")\n"
    }
   ]
  },
  {
   "title": "DMS Key Presses",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "query": "from(bucket: \"sensors\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"DMS\")\n  |> filter(fn: (r) => r[\"_field\"] == \"state\")\n  |> filter(fn: (r) => r[\"device\"] == \"iot-edge-01\")\n  |> filter(fn: (r) => r[\"pi_id\"] == \"PI1\")\n  |> yield(name: \"key_presses\")"
    }
   ]
  },
  {
   "title": "DPIR1",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "query": "from(bucket: \"sensors\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"DPIR1\")\n  |> filter(fn: (r) => r[\"_field\"] == \"state\")\n  |> filter(fn: (r) => r[\"device\"] == \"iot-edge-01\")\n  |> filter(fn: (r) => r[\"pi_id\"] == \"PI1\")\n  |> filter(fn: (r) => r[\"sensor\"] == \"DPIR1\")\n  |> map(fn: (r) => ({ r with _value: if r._value == \"motion_detected\" then 1 else 0 }))\n  |> yield(name: \"mean\")\n"
    }
   ]
  },
  {
   "title": "DS1",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "query": "from(bucket: \"sensors\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"DS1\")\n  |> filter(fn: (r) => r[\"_field\"] == \"state\")\n  |> filter(fn: (r) => r[\"device\"] == \"iot-edge-01\")\n  |> filter(fn: (r) => r[\"pi_id\"] == \"PI1\")\n  |> map(fn: (r) => ({ r with _value: if r._value == \"open\" then 1 else 0 }))\n  |> yield(name: \"state\")\n"
    }
   ]
  },
  {
   "title": "DUS1",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "cm" } },
   "targets": [
    {
     "query": "from(bucket: \"sensors\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"DUS1\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"device\"] == \"iot-edge-01\")\r\n  |> filter(fn: (r) => r[\"pi_id\"] == \"PI1\")\r\n  |> filter(fn: (r) => r[\"sensor\"] == \"DUS1\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")\r\n"
    }
   ]
  },
  {
   "title": "DPIR2",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "query": "from(bucket: \"sensors\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"DPIR2\")\n  |> filter(fn: (r) => r[\"_field\"] == \"state\")\n  |> filter(fn: (r) => r[\"device\"] == \"iot-edge-02\")\n  |> filter(fn: (r) => r[\"pi_id\"] == \"PI2\")\n  |> filter(fn: (r) => r[\"sensor\"] == \"DPIR2\")\n  |> map(fn: (r) => ({ r with _value: if r._value == \"motion_detected\" then 1 else 0 }))\n  |> yield(name: \"mean\")\n"
    }
   ]
  },
  {
   "title": "DPIR3",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "query": "from(bucket: \"sensors\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"DPIR3\")\n  |> filter(fn: (r) => r[\"_field\"] == \"state\")\n  |> filter(fn: (r) => r[\"device\"] == \"iot-edge-03\")\n  |> filter(fn: (r) => r[\"pi_id\"] == \"PI3\")\n  |> filter(fn: (r) => r[\"sensor\"] == \"DPIR3\")\n  |> map(fn: (r) => ({ r with _value: if r._value == \"motion_detected\" then 1 else 0 }))\n  |> yield(name: \"mean\")\n"
    }
   ]
  },
  {
   "title": "DUS2",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "cm" } },
   "targets": [
    {
     "query": "from(bucket: \"sensors\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"DUS2\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"device\"] == \"iot-edge-02\")\r\n  |> filter(fn: (r) => r[\"pi_id\"] == \"PI2\")\r\n  |> filter(fn: (r) => r[\"sensor\"] == \"DUS2\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")\r\n"
    }
   ]
  },
  {
   "title": "DS2",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "query": "from(bucket: \"sensors\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"DS2\")\n  |> filter(fn: (r) => r[\"_field\"] == \"state\")\n  |> filter(fn: (r) => r[\"device\"] == \"iot-edge-02\")\n  |> filter(fn: (r) => r[\"pi_id\"] == \"PI2\")\n  |> map(fn: (r) => ({ r with _value: if r._value == \"open\" then 1 else 0 }))\n  |> yield(name: \"state\")\n"
    }
   ]
  },
  {
   "title": "DHT3",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "query": "from(bucket: \"sensors\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"DHT\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"device\"] == \"iot-edge-02\")\n  |> filter(fn: (r) => r[\"pi_id\"] == \"PI2\")\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "GYRO Sensor",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "query": "from(bucket: \"sensors\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"GYRO\")\n  |> filter(fn: (r) => r[\"_field\"] == \"state\")\n  |> filter(fn: (r) => r[\"device\"] == \"iot-edge-02\")\n  |> filter(fn: (r) => r[\"pi_id\"] == \"PI2\")\n  |> filter(fn: (r) => r[\"sensor\"] == \"GYRO\")\n  |> yield(name: \"gyro_state\")"
    }
   ]
  },
  {
   "title": "4SD Sensor",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {
     "query": "from(bucket: \"sensors\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"4SD\")\n  |> filter(fn: (r) => r[\"_field\"] == \"state\")\n  |> filter(fn: (r) => r[\"device\"] == \"iot-edge-02\")\n  |> filter(fn: (r) => r[\"pi_id\"] == \"PI2\")\n  |> filter(fn: (r) => r[\"sensor\"] == \"4SD\")\n  |> yield(name: \"4sd_state\")"
    }
   ]
  },
  {
   "title": "BTN Press",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "query": "import \"experimental\"\n\nbtn = from(bucket: \"sensors\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"BTN\")\n  |> filter(fn: (r) => r[\"_field\"] == \"state\")\n  |> filter(fn: (r) => r[\"device\"] == \"iot-edge-02\")\n  |> filter(fn: (r) => r[\"pi_id\"] == \"PI2\")\n  |> map(fn: (r) => ({ r with _value: if r._value == \"pressed\" then 1 else 0 }))\n\nbtn_zero_after = btn\n  |> map(fn: (r) => ({ r with _value: 0, _time: experimental.addDuration(d: 1s, to: r._time) }))\n\nunion(tables: [btn, btn_zero_after])\n  |> sort(columns: [\"_time\"])\n  |> yield(name: \"state\")"
    }
   ]
  },
  {
   "title": "DHT1",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "query": "from(bucket: \"sensors\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"DHT\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"device\"] == \"iot-edge-03\")\n  |> filter(fn: (r) => r[\"pi_id\"] == \"PI3\")\n  |> filter(fn: (r) => r[\"sensor\"] == \"DHT1_temperature\" or r[\"sensor\"] == \"DHT1_humidity\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "DHT2",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {
     "query": "from(bucket: \"sensors\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"DHT\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"device\"] == \"iot-edge-03\")\n  |> filter(fn: (r) => r[\"pi_id\"] == \"PI3\")\n  |> filter(fn: (r) => r[\"sensor\"] == \"DHT2_humidity\" or r[\"sensor\"] == \"DHT2_temperature\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "LCD",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 52 },
   "targets": [
    {
     "query": "from(bucket: \"sensors\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"LCD\")\n  |> filter(fn: (r) => r[\"_field\"] == \"state\")\n  |> filter(fn: (r) => r[\"device\"] == \"iot-edge-03\")\n  |> filter(fn: (r) => r[\"pi_id\"] == \"PI3\")\n  |> filter(fn: (r) => r[\"sensor\"] == \"LCD\")\n  |> yield(name: \"lcd_state\")"
    }
   ]
  },
  {
   "title": "BRGB",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 62 },
   "targets": [
    {
     "query": "from(bucket: \"sensors\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"BRGB\")\n  |> filter(fn: (r) => r[\"_field\"] == \"state\")\n  |> filter(fn: (r) => r[\"device\"] == \"iot-edge-03\")\n  |> filter(fn: (r) => r[\"pi_id\"] == \"PI3\")\n  |> filter(fn: (r) => r[\"sensor\"] == \"BRGB\")\n  |> yield(name: \"brgb_state\")"
    }
   ]
  },
  {
   "title": "IR Sensor",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 72 },
   "targets": [
    {
     "query": "from(bucket: \"sensors\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"IR\")\n  |> filter(fn: (r) => r[\"_field\"] == \"state\")\n  |> filter(fn: (r) => r[\"device\"] == \"iot-edge-03\")\n  |> filter(fn: (r) => r[\"pi_id\"] == \"PI3\")\n  |> filter(fn: (r) => r[\"sensor\"] == \"IR\")\n  |> yield(name: \"ir_state\")"
    }
   ]
  }
 ]
}